# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
